language: node_js
node_js: stable
jobs:
  include:
    - stage: "Tests"  
      name: "Review JS code"
      script: "node deploy/lint.js"
    - name: "Test runtime environment"
      script: "node deploy/minify.js"
      script: "node deploy/run-server.js"
    - stage: "Build & deploy"
      name: Minify & Deploy
      script: "node deploy/prod-cleanup.js"
      script: "node deploy/minify.js"
      deploy:
        provider: pages:git
        token: $GITHUB_REPO_TOKEN
        edge: true # opt in to dpl v2
        target_branch: master
        keep_history: false
        commit_message: "Automagic deploy"
        on:
          branch: source
branches:
  except:
    master