language: node_js
node_js: stable
jobs:
  include:
    - stage: "tests"
      name: "check code quailty"
      script: "node deploy/run-lint.js"
    - name: "test runtime environment"
      script: "node deploy/run-live-source-test.js"
    - stage: "build & deploy"
      if: type != pull_request
      name: "insert, minify, push"
      script: "node deploy/run-build.js"
      deploy:
        provider: pages:git
        token: $GITHUB_REPO_TOKEN
        edge: true # opt in to dpl v2
        target_branch: master
        keep_history: false
        commit_message: "Automagic deploy"
        on:
          branch: source
    - stage: "test production"
      if: type != pull_request
      name: "test runtime environment"
      script: "node deploy/run-live-prod-test.js"
branches:
  only:
    source