language: node_js
node_js: stable
jobs:
  include:
    - stage: "Code review"
      
      name: Linting
      script: "node deploy/lint.js"
      
    - stage: "Build & Deploy"
      name: Minify
      script: "node deploy/minify.js"
      name: Deploy
      deploy:
        provider: pages:git
        token: $GITHUB_REPO_TOKEN
        edge: true # opt in to dpl v2
        target_branch: master
        keep_history: false
        commit_message: "Automatic deploy"
        on:
          branch: source
branches:
  except:
    master