language: node_js
node_js: stable
jobs:
  include:
    - stage: "Tests"
      name: "Review HTML"
      script: "node deploy/lint.js"
    - name: "Review JS"
      script: "node deploy/lint.js"
    - name: "Review CSS"
      script: "node deploy/lint.js"
    - name: "Test runtime environment"
      script: "node deploy/test-live.js"
    - stage: "Build & deploy"
      name: Minify & Deploy
      script: "node deploy/minify.js"
      deploy:
        provider: pages:git
        token: $GITHUB_REPO_TOKEN
        edge: true # opt in to dpl v2
        target_branch: master
        keep_history: false
        commit_message: "Automagic deploy"
        on:
          branch: source
    - stage: "test production"
      name: "test runtime environment"
      script: "node deploy/test-live.js"
branches:
  except:
    master