[build]
    publish = "public/"
    command = "npm run build"

[[headers]]

    for = "/*"

    [headers.values]
        X-Frame-Options = "SAMEORIGIN"
        X-Content-Type-Options = "nosniff"
        Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
        Content-Security-Policy = "default-src 'none'; style-src 'self'; script-src 'self'"