[build]
    publish = "public/"
    command = "npm run build"

[[headers]]

    for = "/*"

    [headers.values]
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "strict-origin-when-cross-origin"
        Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
        Content-Security-Policy = """
            default-src 'none';
            style-src 'self';
            script-src 'self';
            img-src 'self';
            manifest-src 'self';
            connect-src 'self';
            frame-ancestors 'none';
            base-uri 'self';
            form-action 'none'
        """
        Permissions-Policy = """
            camera=(),
            microphone=(),
            payment=(),
            geolocation=()
        """
