[build]
    publish = "public/"
    command = "npm run build"

[[headers]]

    for = "/*"

    [headers.values]
        X-Frame-Options = "SAMEORIGIN"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "strict-origin-when-cross-origin"
        Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
        Content-Security-Policy = "default-src 'self'"
        Feature-Policy = "camera 'none'; microphone 'none'; payment 'none'; geolocation 'none'"